### ISSUE TITLE
Regarding code release.

### ISSUE THREAD

**Issue by paras-jain** [Thoriri/EEG-TCNet#1]
Will you be releasing the code of the paper, EEG-TCNet: An Accurate Temporal Convolutional Network for Embedded Motor-Imagery Brain–Machine Interfaces? If you could please tell when you'd be able to release the code, that would be great.

**Comment by Thoriri** [comment]
Hi!

Yes the code will be released at the same time as the SMC 2020 conference will be held. (11.10.20 -14.10.20)
